### PR TITLE
Fix commands in templates and make them easier to read

### LINKED ISSUE #22: Borg-backup mount bug for multiple servers
As discovered in PR #19 by @noplanman : the borg-backup mount command accepts 3 additional parameters: the name of the backup server, the backup id and the mount path. In the current implementation, the server name is ignored. In case of multiple servers, the backup will always be mounted from the last server in your list.

So: borg-backup mount whatever-you-type-here 20200318-0931 /mnt/
will also mount the backup from the last server in your server list.
This should be fixed.

### PR DESCRIPTION
**Pull request by noplanman**
- Fix `mount` command as discovered in #19 
- Introduce new `id` parameter to backup servers, as a shortcut for usage in commands
- Allow all commands to define a specific backup server to run the command on (or leave empty to run on all of them)
- Clean up scripts and deduplicate by using [Jinja Macros](https://jinja.palletsprojects.com/en/2.11.x/templates/#macros)

Closes #22

### CODE REVIEW

File: templates/prune.sh.j2 [hunk 1]
```diff
@@ -1,27 +1,39 @@
...
+{{ b.user }}@{{ b.fqdn }}:{{ b.home }}{{ b.pool }}/{{ h }}
+{%- endif %}
+{% endmacro -%}
+
+# This script is intended to run on a trusted management station
+# to purge borg repos in append-only mode.
 # Don't put it on the backup server, it contains all borg secrets!
 
 {% for h in groups['all'] %}
-  {% if hostvars[h].borgbackup_required | default(True) -%}
```
Comment (noplanman) [inline templates/prune.sh.j2:9]: @dverhelst @stroobl 
I noticed my change on this line is failing the test, because I don't define a default.

In my opinion, this should default to false, as only hosts that require borg should be added to the prune script right?!

Comment (dverhelst) [reply templates/prune.sh.j2:9]: It looks like this loop is not running correctly on molecule at least. I'm identifying the problem ...

Comment (dverhelst) [reply templates/prune.sh.j2:9]: I'm confused myself :)

The following code temporary added to the prune.sh template:

```
# with default True
{% for h in groups['all'] %}
#  {{ h }} : {{ hostvars[h].borgbackup_required|default(True) }}
{% endfor %}
# with default False
{% for h in groups['all'] %}
#  {{ h }} : {{ hostvars[h].borgbackup_required|default(False) }}
{% endfor %}

```
Resulted in this:

```
# with default True
#  default-server-debian-10 : False
#  default-management-debian-10 : True
#  default-client-debian-10 : True
# with default False
#  default-server-debian-10 : False
#  default-management-debian-10 : False
#  default-client-debian-10 : False
```

@stroobl  care to chime in? This is 'odd' behaviour.

Comment (dverhelst) [reply templates/prune.sh.j2:9]: I'm confused myself :)

The following code temporary added to the prune.sh template:

```
# with default True
{% for h in groups['all'] %}
#  {{ h }} : {{ hostvars[h].borgbackup_required|default(True) }}
{% endfor %}
# with default False
{% for h in groups['all'] %}
#  {{ h }} : {{ hostvars[h].borgbackup_required|default(False) }}
{% endfor %}

```
Resulted in this:

```
# with default True
#  default-server-debian-10 : False
#  default-management-debian-10 : True
#  default-client-debian-10 : True
# with default False
#  default-server-debian-10 : False
#  default-management-debian-10 : False
#  default-client-debian-10 : False
```

@stroobl  care to chime in? This is 'odd' behaviour.

Comment (stroobl) [reply templates/prune.sh.j2:9]: Not sure what @dverhelst is trying to prove here :), but I agree with @noplanman that the default should be false.

**Comment by stroobl** [comment]
This looks like a nice improvement. Are you already using the changed code?
Seen the amount of changes in the script I would like to test it thoroughly.

**Comment by noplanman** [comment]
I'll fix up the tests, as they are expecting certain output which has changed by modifying the script.

@stroobl Yes, I'm using these in production with no problems.

**Comment by noplanman** [comment]
@stroobl @dverhelst 
Any idea why `borgbackup_required` needs to be defined explicitly even though it's set to `true` as a default value?

File: templates/prune.sh.j2 (hunk 1 above)
Comment (noplanman) [reply templates/prune.sh.j2:9]: @dverhelst That is expected behaviour, since the `borgbackup_required` variable is set to `False` in `default/molecule.yml` for the `borgbackup_servers` group.
So defaults apply to the client and management system, whereas the server is correctly `False` in both cases.

Or did I miss something you wanted to point out?

**Comment by stroobl** [comment]
> @stroobl @dverhelst
> Any idea why `borgbackup_required` needs to be defined explicitly even though it's set to `true` as a default value?

I think that's required. Actually I just removed it (running from your branch) and the tests still pass for that part. Can you please revert all changes of variables in molecule yaml?

File: molecule/centos/molecule.yml [hunk 2]
```diff
@@ -69,6 +69,9 @@ provisioner:
           - "/root"
           - "/var/log"
           - "/home"
+        borgbackup_install_from_pkg: false
+      clients:
+        borgbackup_required: true
```
Comment (stroobl) [inline molecule/centos/molecule.yml:74]: Please revert the changes in this file.

File: molecule/clients/molecule.yml [hunk 3]
```diff
@@ -164,6 +164,9 @@ provisioner:
           - "/root"
           - "/var/log"
           - "/home"
+        borgbackup_install_from_pkg: false
+      clients:
+        borgbackup_required: true
```
Comment (stroobl) [inline molecule/clients/molecule.yml:169]: Please revert the changes in this file.

File: molecule/default/molecule.yml [hunk 4]
```diff
@@ -58,6 +58,8 @@ provisioner:
           monthly: 6
           yearly: 1
         borgbackup_management_station: default-management-debian-10
+      clients:
+        borgbackup_required: true
```
Comment (stroobl) [inline molecule/default/molecule.yml:62]: Please revert the changes in this file.

File: molecule/lamp/molecule.yml [hunk 5]
```diff
@@ -44,6 +44,8 @@ provisioner:
             home: /var/backup/
             pool: repos
             options: ""
+      clients:
+        borgbackup_required: true
```
Comment (stroobl) [inline molecule/lamp/molecule.yml:48]: Please revert the changes in this file.

File: molecule/multiple/molecule.yml [hunk 6]
```diff
@@ -67,6 +67,8 @@ provisioner:
           - "/root"
           - "/var/log"
           - "/home"
+      clients:
+        borgbackup_required: true
```
Comment (stroobl) [inline molecule/multiple/molecule.yml:71]: Please revert the changes in this file.

File: molecule/ubuntu/molecule.yml [hunk 7]
```diff
@@ -58,6 +58,8 @@ provisioner:
           monthly: 6
           yearly: 1
         borgbackup_management_station: ubuntu-management-ubuntu-bionic
+      clients:
+        borgbackup_required: true
```
Comment (stroobl) [inline molecule/ubuntu/molecule.yml:62]: Please revert the changes in this file.

**Comment by noplanman** [comment]
@stroobl Those failing tests are due to the default value of `borgbackup_required` being set to false. The issue is what I described in my comment above, that the variable set in `defaults/main.yml` isn't being taken into account and it's undefined when the prune script is being created. That's why the tests fail, because the prune script doesn't have any hosts written into it, thus not finding the `borg prune -v` text that it's searching for.

For that reason, I've set the variable in the tests for the clients.

> Actually I just removed it (running from your branch) and the tests still pass for that part.

Erm, well it fails for me, and clearly for you too, so not sure which part you meant with this 🤔

File: templates/prune.sh.j2 (hunk 1 above)
Comment (stroobl) [reply templates/prune.sh.j2:9]: @noplanman I re-tested and now I understand what's going wrong.
In the roles defaults/main.yml we have:
```
borgbackup_required: true
```
Now in prune.sh we put in the comment above here:
```
{%     if hostvars[h].borgbackup_required | default(False) and inventory_hostname == hostvars[h].borgbackup_management_station %}
```
This should be default(True) to match the role default. If you do that, you can remove your changes to molecule.yml as I requested in my review, since that didn't make sense to me. (but I didn't see this link at first)
Sorry for the confusion.

Comment (noplanman) [reply templates/prune.sh.j2:9]: @stroobl Ok, will revert and change this then 👍

**Comment by noplanman** [comment]
Seems the failing build is due to some system issue, not the role itself.

@stroobl Can you restart the failed ones?

**Comment by noplanman** [comment]
@stroobl Is there anything else you'd like to comment on regarding this PR? 😇

**Comment by stroobl** [comment]
@noplanman there still to open remarks for molecule.yml that should be reverted if I'm not mistaken. I already tried to restart the build, but it still fails for one reason or another. I still have to look into that (quite busy lately), but I don't think it's related to your changes.

**Comment by noplanman** [comment]
Have reverted those changes, they seem to have slipped in when merging master back 😬 

Regarding the failing tests, it's strange, because they're only failing on Travis, local testing works perfectly. I'll investigate and see what's up 👌

**Comment by noplanman** [comment]
Seems to be some issue when installing multiple packages together, that some dependency problem occurs.
I've tested by installing the `redhat-lsb-core` package first and then the others, which now works correctly. So it seems this is upstream, which has just popped up now and might just as well go away again in the future.
You can check this [successful build](https://travis-ci.org/github/noplanman/ansible-role-borgbackup/jobs/684041726) from [my branch](https://github.com/fiaasco/borgbackup/compare/fiaasco:d022da2...noplanman:ec71ac0#diff-9df345bac148ba1d3775c4b1c41c7801) I'm busy working on.

Best we first get a fix for the tests in, then merge that into here, to make sure all tests work correctly.
